# Generated by Django 5.1.2 on 2024-10-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('catigory', models.CharField(choices=[('Computer Science', 'Computer Science'), ('physics', 'physics'), ('Material science', 'Material science'), ('chemistry', 'chemistry'), ('mathematics', 'mathematics')], max_length=255)),
                ('is_taken', models.BooleanField(default=False)),
            ],
        ),
    ]
