# Generated by Django 5.1.2 on 2024-10-18 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('students', '0002_student_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(auto_now_add=True)),
                ('to_date', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lend_book', to='books.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lend_student', to='students.student')),
            ],
        ),
    ]
