# Generated by Django 4.2.16 on 2024-10-19 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_lendbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_book', to='books.book')),
            ],
        ),
    ]
