# Generated by Django 4.2.16 on 2024-10-20 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_lostbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostLend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_lend', to='books.lendbook')),
            ],
        ),
        migrations.DeleteModel(
            name='LostBook',
        ),
    ]
