# Generated by Django 4.2.16 on 2024-10-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_lostlend_delete_lostbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='copies',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('Graduation thesis', 'Graduation thesis'), ('Book', 'Book')], default='Book', max_length=255),
        ),
    ]
