# Generated by Django 4.2.16 on 2024-10-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_copies_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('Graduation thesis', 'Graduation thesis'), ('Book', 'Book'), ('Dictionary', 'Dictionary')], default='Book', max_length=255),
        ),
    ]
