# Generated by Django 4.2.16 on 2024-10-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_copies_alter_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='code',
            field=models.CharField(help_text='---/--', max_length=100),
        ),
    ]
