# Generated by Django 4.2.16 on 2024-10-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_book_code_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='copy',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
