# Generated by Django 4.2.16 on 2024-10-31 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_copy_is_taken_copy_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lendbook',
            name='book',
        ),
        migrations.AddField(
            model_name='lendbook',
            name='copy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lend_copy', to='books.copy'),
            preserve_default=False,
        ),
    ]
