# Generated by Django 4.2.16 on 2024-10-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.PositiveIntegerField(),
        ),
    ]
